# https://docs.docker.com/compose/compose-file/compose-file-v3/
version: '3.9'
services:
  web:
    build: .
    ports:
      - '5000:5000'
  redis:
    # https://hub.docker.com/_/redis
    image: 'redis:alpine'
